package pokemon;

import static pokemon.StrengthType.*;

public class StrengthMatrix {

    StrengthType[][] strengthMatrix = {
        {NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,LESS_DAMAGE,NO_DAMAGE,NEUTRAL,NEUTRAL,LESS_DAMAGE,NEUTRAL},
        {NEUTRAL,LESS_DAMAGE,LESS_DAMAGE,NEUTRAL,MORE_DAMAGE,MORE_DAMAGE,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,MORE_DAMAGE,LESS_DAMAGE,NEUTRAL,LESS_DAMAGE,NEUTRAL,MORE_DAMAGE,NEUTRAL},
        {NEUTRAL,MORE_DAMAGE,LESS_DAMAGE,NEUTRAL,LESS_DAMAGE,NEUTRAL,NEUTRAL,NEUTRAL,MORE_DAMAGE,NEUTRAL,NEUTRAL,NEUTRAL,MORE_DAMAGE,NEUTRAL,LESS_DAMAGE,NEUTRAL,NEUTRAL,NEUTRAL},
        {NEUTRAL,NEUTRAL,MORE_DAMAGE,LESS_DAMAGE,LESS_DAMAGE,NEUTRAL,NEUTRAL,NEUTRAL,NO_DAMAGE,MORE_DAMAGE,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,LESS_DAMAGE,NEUTRAL,NEUTRAL,NEUTRAL},
        {NEUTRAL,LESS_DAMAGE,MORE_DAMAGE,NEUTRAL,LESS_DAMAGE,NEUTRAL,NEUTRAL,LESS_DAMAGE,MORE_DAMAGE,LESS_DAMAGE,NEUTRAL,LESS_DAMAGE,MORE_DAMAGE,NEUTRAL,LESS_DAMAGE,NEUTRAL,LESS_DAMAGE,NEUTRAL},
        {NEUTRAL,LESS_DAMAGE,LESS_DAMAGE,NEUTRAL,MORE_DAMAGE,LESS_DAMAGE,NEUTRAL,NEUTRAL,MORE_DAMAGE,MORE_DAMAGE,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,MORE_DAMAGE,NEUTRAL,LESS_DAMAGE,NEUTRAL},
        {MORE_DAMAGE,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,MORE_DAMAGE,NEUTRAL,LESS_DAMAGE,NEUTRAL,LESS_DAMAGE,LESS_DAMAGE,LESS_DAMAGE,MORE_DAMAGE,NO_DAMAGE,NEUTRAL,MORE_DAMAGE,MORE_DAMAGE,LESS_DAMAGE},
        {NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,MORE_DAMAGE,NEUTRAL,NEUTRAL,LESS_DAMAGE,LESS_DAMAGE,NEUTRAL,NEUTRAL,NEUTRAL,LESS_DAMAGE,LESS_DAMAGE,NEUTRAL,NEUTRAL,NO_DAMAGE,MORE_DAMAGE},
        {NEUTRAL,MORE_DAMAGE,NEUTRAL,MORE_DAMAGE,LESS_DAMAGE,NEUTRAL,NEUTRAL,MORE_DAMAGE,NEUTRAL,NO_DAMAGE,NEUTRAL,LESS_DAMAGE,MORE_DAMAGE,NEUTRAL,NEUTRAL,NEUTRAL,MORE_DAMAGE,NEUTRAL},
        {NEUTRAL,NEUTRAL,NEUTRAL,LESS_DAMAGE,MORE_DAMAGE,NEUTRAL,MORE_DAMAGE,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,MORE_DAMAGE,LESS_DAMAGE,NEUTRAL,NEUTRAL,NEUTRAL,LESS_DAMAGE,NEUTRAL},
        {NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,MORE_DAMAGE,MORE_DAMAGE,NEUTRAL,NEUTRAL,LESS_DAMAGE,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NO_DAMAGE,LESS_DAMAGE,NEUTRAL},
        {NEUTRAL,LESS_DAMAGE,NEUTRAL,NEUTRAL,MORE_DAMAGE,NEUTRAL,LESS_DAMAGE,LESS_DAMAGE,NEUTRAL,LESS_DAMAGE,MORE_DAMAGE,NEUTRAL,NEUTRAL,LESS_DAMAGE,NEUTRAL,MORE_DAMAGE,LESS_DAMAGE,LESS_DAMAGE},
        {NEUTRAL,MORE_DAMAGE,NEUTRAL,NEUTRAL,NEUTRAL,MORE_DAMAGE,LESS_DAMAGE,NEUTRAL,LESS_DAMAGE,MORE_DAMAGE,NEUTRAL,MORE_DAMAGE,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,LESS_DAMAGE,NEUTRAL},
        {NO_DAMAGE,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,MORE_DAMAGE,NEUTRAL,NEUTRAL,MORE_DAMAGE,NEUTRAL,LESS_DAMAGE,NEUTRAL,NEUTRAL},
        {NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,MORE_DAMAGE,NEUTRAL,LESS_DAMAGE,NO_DAMAGE},
        {NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,LESS_DAMAGE,NEUTRAL,NEUTRAL,NEUTRAL,MORE_DAMAGE,NEUTRAL,NEUTRAL,MORE_DAMAGE,NEUTRAL,LESS_DAMAGE,NEUTRAL,LESS_DAMAGE},
        {NEUTRAL,LESS_DAMAGE,LESS_DAMAGE,LESS_DAMAGE,NEUTRAL,MORE_DAMAGE,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,MORE_DAMAGE,NEUTRAL,NEUTRAL,NEUTRAL,LESS_DAMAGE,MORE_DAMAGE},
        {NEUTRAL,LESS_DAMAGE,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,MORE_DAMAGE,LESS_DAMAGE,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,MORE_DAMAGE,MORE_DAMAGE,LESS_DAMAGE,NEUTRAL}
    };
}
